apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: token-secret
  annotations:
    kubernetes.io/service-account.name: autoscaler-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoscaler-sa
secrets:
  - name: token-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: autoscaler-role
rules:
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch", "update", "patch"] 
    #verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: autoscaler-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: autoscaler-role 
subjects:
- namespace: default
  kind: ServiceAccount
  name: autoscaler-sa

