apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler
  labels:
    app: autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaler
  template:
    metadata:
      labels:
        app: autoscaler
    spec:
      serviceAccountName: autoscaler-sa
      containers:
        - name: autoscaler
          image: olesiapoz/autoscaler:SMAx4x90x10x90x0.4RT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1000m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          volumeMounts:
          - name: azurefile
            mountPath: /root/
      nodeSelector:
        type: infra
      volumes:
      - name: azurefile
        persistentVolumeClaim:
          claimName: azurefile

